---
version: '3'
services:
  absolute_api:
    # real image reference would be similar to below for better configurability
    #image: "${DOCKERHUB_SERVER}/${ABSOLUTE_API_IMAGE}:${ABSOLUTE_API_VERSION}"
    build: ./absolute_api
    restart: always
    ports:
     - "5000:5000"
    volumes:
    # config should be externalized from docker image.
     - ./absolute_api.properties:/absolute_api.properties:ro
